### ISSUE TITLE
Compare date value with current date from server 

### ISSUE THREAD

**Issue by Miirwan** [ndresx/react-countdown#58] opened 2019-10-22 22:30 UTC
How to compare date value with current date from server  not  date.now() ?

**Comment by ndresx** [comment] 2019-10-22 23:05
Hi, you could calculate the difference between the server date and the current date `Date.now()` and create a callback function which returns `Date.now()` plus/minus this calculated difference. The callback can then applied through the [`now`](https://github.com/ndresx/react-countdown#now) prop.

Maybe something like this?
https://codesandbox.io/s/intelligent-brahmagupta-hnkck

**Comment by Miirwan** [comment] 2019-10-22 23:47
Hi, in my situation I use the countdown to calculate the time remaining to pass a test so I pass in the prop `date` the expected start date of the test and I want to compare it with the current date of my server, to avoid the problem local time or machine . 

I hope you have understood my situation

Here's some parts of the code :
`
  return (
    <Countdown
      date={new Date(test.startDate).getTime() : Date.now() + duration * 1000}
      renderer={data =>
        renderer
          ? renderer(data, dangerTime)
          : defaultRenderer(data, dangerTime)
      }
      onComplete={onComplete}
      zeroPadTime={2}
    />
  );`

**Comment by ndresx** [comment] 2019-10-23 00:42
It doesn't really matter whether you adjust the countdown's end `date` or apply the callback function as linked before to accomplish this. I guess that `test.startDate` is also a server-based time? So the only thing you would have to do is to calculate the difference between client-/server-time at one point and that's it, but you need to know about the server's time at one point at least.

**Comment by Miirwan** [comment] 2019-10-23 13:22
exactly the `test.statDate` is also a server-based time , i think it's clear for me about what you said , thank you for your feedback

**Comment by ndresx** [comment] 2019-10-23 20:31
You're welcome! Let me know in case you have any follow-up questions!

**Comment by Miirwan** [comment] 2019-10-24 01:22
i try to calculate the difference between a future time & current time of system in mill 
`diff = 1571958000000 - 1571879231178 ` then i  send it to prop `date={diff}`

i got this error : 
`Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.` 

where im wrong ?

**Comment by ndresx** [comment] 2019-10-24 10:25
Looks like you are triggering a state update from within one of the render functions, or need to persist the calculated difference somewhere in state first and then pass it into `date`. Or is this error caused by the countdown itself?

**Comment by ndresx** [comment] 2019-11-10 18:13
Closing this, please feel free to re-open or create a new issue if you have more questions. Thank you!

**Closed by ndresx** 2019-11-10 18:13 UTC
Labels: question
