### ISSUE TITLE
NaN on IOS

### ISSUE THREAD

**Issue by danielt69** [ndresx/react-countdown#48] opened 2019-07-30 10:01 UTC
Hi,
I am having some issues on Safari and Chrome on IOS only.
this is the output of the counter:  "NaN : NaN : NaN"

Iphone 7s plus
IOS veersion 12.4

**Comment by ndresx** [comment] 2019-07-30 18:14
Hi, thanks for your report!

Could you tell me please which version of the countdown you have used?
Do you see the same behavior on the demo builds? (e.g. https://codesandbox.io/s/QWoK01R7M)

**Comment by danielt69** [comment] 2019-08-06 10:44
I used version 2.1.1
Didn't see any errors.
The demo page is working fine....

**Comment by ndresx** [comment] 2019-08-07 07:32
I will try to check it out asap, but it almost sounds like that some input props like the `date` or `now` could be wrong and lead to this issue if the demo itself is working.

**Comment by anthonyvialleton** [comment] 2019-08-14 13:34
I confirm that also on iOS this bug still occurs. I'm passing a date string formatted like below : '2019-08-14 15:19:00' (not even a vanilla Date). 

To fix it I have to pass a different type of content for the `date` prop such as a `moment` date type instead.

**Comment by ndresx** [comment] 2019-08-14 16:52
Please see https://github.com/ndresx/react-countdown/issues/49 as this might be the reason for why it's not working on Mac/iOS/Safari.

**Comment by ndresx** [comment] 2019-08-16 15:00
I'm closing this as the problem most likely occurs when using an invalid date format. I have updated the docs what the valid formats are https://github.com/ndresx/react-countdown#date.

Feel free to reopen if this issue still occurs - even with a valid date - but please provide more details then to be able to reproduce it. Thank you!

**Closed by ndresx** 2019-08-16 15:00 UTC
Labels: bug, question
