### ISSUE TITLE
When i click other buttons, it affects the timer in a messed up way

### ISSUE THREAD

**Issue by Perelyn-sama** [ndresx/react-countdown#110] opened 2020-12-18 16:21 UTC
I have a button to increment and decrement the value of the timer but it doesn't work and when other buttons that are not related to the timer are clicked the timer's value changes
https://stackblitz.com/edit/fcc-timer

**Comment by ndresx** [comment] 2020-12-18 19:01
Hi, the problem is that the `renderer` function gets redeclared on every re-render, which unfortunately causes the countdown to update due to the failing props comparison and then tries to update the time.

I'm not sure if your example can be fixed with the current version to be honest unless you transform your functional component into a class component (then it should work without problems). It could eventually also work to mount this functionality within the `renderer` function (with a new component). I will try to take a look at this and see what I can do.

**Comment by Perelyn-sama** [comment] 2020-12-18 20:12
Please do, I've been working with hooks for the last 3 months going back to class components is like hell and I need this urgently. Thanks

**Comment by eduard-s** [comment] 2021-02-07 08:50
even if you have a class component it fails - not sure what is a workaround here  
1. if I pause it via api - and then click on other buttons which cause the re-render it will update the timer value
2. if again I will resume it via api - it returns correct time and starts counting again..
3. so the problem is when it is stopped it shows the countdown running when we cause the reredner

**Comment by eduard-s** [comment] 2021-02-07 09:09
the workaround here is to have a state vars for the current time and set it in the onPause callback of this timer. and in render check if it is paused then use these state values instead of render function params - this can be actually integrated in the bugfix as well

**Closed** 2021-05-08 19:34 UTC
Labels: bug
