### ISSUE TITLE
Countdown is not ticking when I pass date and now property.

### ISSUE THREAD

**Issue by DeepakkumarArumugam** [ndresx/react-countdown#1] opened 2017-08-29 04:38 UTC
Your help will be highly appreciated!!!!
This component is awesome. I am using date property as a enddate and Now property function which returns current date and time as per documentation. However time is not ticking down if i custom now function.
But if i use default Date.now() inside now function, Countdown start ticks...

**Comment by ndresx** [comment] 2017-09-02 15:09
Hi, what exactly do you pass for `now`? You could also alter this demo if you want https://codesandbox.io/s/v871l3qvm7.

**Comment by halukugurlu** [comment] 2017-10-26 18:23
I second @DeepakkumarArumugam 's problem.

Any quick solution to that?

I pass a callback that returns the current timestamp (retrieved from the server) for the "now" prop.

Could you suggest a solution?

**Comment by ndresx** [comment] 2017-10-26 21:34
@halukugurlu I think I know what the problem is and the doc is not clear about that (I'm sorry). 

Based on what you said I guess you are always returning the same value, while the default value for `now` is actually only a reference to `Date.now`. `now` is getting invoked on every tick (default = `Date.now()`) which is returning a new updated value (the current timestamp), while your's probably isn't when it's getting statically returned from the server?

Could you maybe post an example please of how you are using `now`?

**Comment by halukugurlu** [comment] 2017-10-26 21:40
@ndresx I am super glad to hear back from you. The component is awesome except the edgecase I am trying to solve now.
You are absolutely right about your guess. I noticed that after debugging the code all day today.

I wanted to use the countdown timer for an event, but organizers do not want to trust client's computer clock (Date.now)

so I need to find a way to make the countdown timer work in a way that, it will calculate the difference (**event's date/time  minus  server timestamp**) and set the countdown timer accordingly.

I think the prop controlled is intended for that but that also broke when I pass true.

so how can I accomplish that? (I don't have a luxury to use Date.now for dynamic ticking)

**Comment by ndresx** [comment] 2017-10-26 21:55
Could you try to use the `onTick` handler and change the requested server time you have probably stored somewhere on each tick (at least the one you are returning via `now()`)? It would basically update itself then.

**Comment by halukugurlu** [comment] 2017-10-26 22:03
so on each tick, I will use `delta` returned from `onTick` and pass it back again to `now` prop?

**Comment by halukugurlu** [comment] 2017-10-26 22:27
<img width="838" alt="screen shot 2017-10-26 at 8 45 54 pm" src="https://user-images.githubusercontent.com/7146285/32080023-4e4b327e-ba7b-11e7-9d08-a997aceba0d1.png">

**Comment by ndresx** [comment] 2017-10-26 22:33
Take a look at this one https://codesandbox.io/s/3rjkzl523p. Does this help in any way?

While not directly related to this issue, I will investigate a bit further on this during the upcoming days and change the docs.

**Comment by halukugurlu** [comment] 2017-10-27 21:45
@ndresx yes it worked nicely. I am not very clear about the logic but it works good.
Thank you so much for your support.

**Comment by ndresx** [comment] 2017-10-28 14:35
Glad this works. It's just a _replacement_ of what `Date.now` is doing in the background since you cannot rely on it. I have also updated the documentation to be at least a bit clearer on its usage. Thank you and closing this for now!

**Closed by ndresx** 2017-10-28 14:35 UTC
Labels: documentation
